# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '2'

networks:
  proxy:
    external: true
  internal:
    external: 
      name: demandjs.localhost

services:
  api:

    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demandjs-api.rule=Host(`api.demandcluster.com`)"
      - "traefik.http.routers.demandjs-api.tls=true"
      - "traefik.http.routers.demandjs-api.entrypoints=websecure"
      - "traefik.http.routers.demandjs-api.service=demandjs-api-service"
      - "traefik.http.services.demandjs-api-service.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

    image: docker.pkg.github.com/demandcluster/reaction/reaction-prod:12.14.1-v1
    depends_on:
      - mongo
    env_file:
      - ./.env
 
  mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger

    networks:
      - internal
    ports:
     - "32828:27017"
    volumes:
      - mongo-db4:/data/db
    
volumes:
  mongo-db4: